### ISSUE TITLE
ETA for box annotation type support?

### ISSUE THREAD

**Issue by patakijv** [compwright/chartjs-plugin-draggable#2]
Just found your plugin and it works great for lines so far! It took me only minutes to implement - yay!
I also want to use it for box annotations and I noticed you have that on the todo list.
Is this a "way out there" type of todo or is it actively being developed and could be ready soon?

Is there an experimental branch for an already started effort for box annotation support I could take a look at if this isn't on the near horizon?

**Comment by compwright** [comment]
We just need a willing volunteer to step up to the plate and make it happen. There is no timeline set for any feature development.
